### PR TITLE
FORUM-1251 : removed forum war refs

### PR DESCRIPTION
**Pull request by mtrabelsi**

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
I cannot build this PR, I got the following message :

_[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project org.exoplatform.platform.distributions:plf-dependencies:4.4.x-SNAPSHOT (/home/thomas/exoplatform/sources/exo/platform-public-distributions/plf-dependencies/pom.xml) has 4 errors
[ERROR]     'dependencies.dependency.version' for org.exoplatform.forum:forum-forumResources:war is missing. @ org.exoplatform.platform.distributions:plf-dependencies:[unknown-version], /home/thomas/exoplatform/sources/exo/platform-public-distributions/plf-dependencies/pom.xml, line 332, column 17
[ERROR]     'dependencies.dependency.version' for org.exoplatform.forum:forum-forumResources:pom is missing. @ org.exoplatform.platform.distributions:plf-dependencies:[unknown-version], /home/thomas/exoplatform/sources/exo/platform-public-distributions/plf-dependencies/pom.xml, line 337, column 17
[ERROR]     'dependencies.dependency.version' for org.exoplatform.forum:forum-poll-webapp:war is missing. @ org.exoplatform.platform.distributions:plf-dependencies:[unknown-version], /home/thomas/exoplatform/sources/exo/platform-public-distributions/plf-dependencies/pom.xml, line 342, column 17
[ERROR]     'dependencies.dependency.version' for org.exoplatform.forum:forum-poll-webapp:pom is missing. @ org.exoplatform.platform.distributions:plf-dependencies:[unknown-version], /home/thomas/exoplatform/sources/exo/platform-public-distributions/plf-dependencies/pom.xml, line 347, column 17_

**Comment by mtrabelsi** [comment]
Should be fixed now, please check it again.

**Comment by thomasdelhomenie** [comment]
LGTM

**Comment by thomasdelhomenie** [comment]
Merged

**Pull request closed without merging**
