### PR TITLE
Run on JDK 9

### PR DESCRIPTION
**Pull request by thomasdelhomenie**
* Remove references to Java 7 since we do not support it
* Update version parsing and tests to support [new JDK 9 version scheme](http://openjdk.java.net/jeps/223)
* Add required modules : java.activation and java.xml.bind

### CODE REVIEW

**Comment by boubaker** [comment]
I think we should delete parameters for PERMSIZE because it was deprecated in JAVA 8 too:
-XX:MaxPermSize=size
-XX:PermSize=size

**Comment by thomasdelhomenie** [comment]
Agreed, and done.

**Comment by boubaker** [comment]
I think we should delete XX:MaxMetaspaceSize as well

**Comment by thomasdelhomenie** [comment]
Why ? This option is recognized by JDK 8 and 9.

**Comment by thomasdelhomenie** [comment]
Why ? This option is recognized by JDK 8 and 9.

**Comment by boubaker** [comment]
As you can see here:
https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/considerations.html
The amount of native memory that can be used for class metadata is by default unlimited.
IMO, we shouldn't put a limit for it. But it can be considered and treated apart in a different study (for JVM options tuning) if you think so.

**Comment by thomasdelhomenie** [comment]
Yes, I think the goal is here is only to make PLF run on JDK 9. We can treat your remark in a dedicated issue.

**Review by boubaker — DISMISSED** [review]

**Review by boubaker — APPROVED** [review]

**Pull request merged**
